name: Github Actions

# trigger
on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest -s
      
    - name: Send notifications on failure
      if: failure()
      run: echo "Build failed."
